# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore "PonVenue/PonVenue.csproj"

    - name: Build app
      run: dotnet build "PonVenue/PonVenue.csproj" -c Release --no-restore

    - name: Publish App
      run: dotnet publish "PonVenue/PonVenue.csproj" -c Release -o ./ponvenue


    - name: whoami
      uses: appleboy/ssh-action@v0.1.4
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: whoami 
