# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore Dependencies
      run: dotnet restore "PonVenue/PonVenue.csproj"

    - name: Build app
      run: dotnet build "PonVenue/PonVenue.csproj" -c Release --no-restore

    - name: Publish App
      run: dotnet publish "PonVenue/PonVenue.csproj" -c Release -o ./ponvenue



    - name: Copy To VPS
      uses: appleboy/scp-action@web
      env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
      with:
          source: "./ponvenue"
          target: "/var/www"
          
    - name: cmod
      uses: appleboy/ssh-action@web
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: chmod -R 777 /var/www/ponvenue    
          
    - name: Copy  Site File
      uses: appleboy/ssh-action@web
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: cp /var/www/ponvenue/ponvenue.conf /etc/apache2/sites-available 
      
    - name: Enable Site
      uses: appleboy/ssh-action@web
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: | 
            cd /etc/apache2/sites-available & a2ensite ponvenue.conf    
          
    - name: Copy Service
      uses: appleboy/ssh-action@web
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: cp /var/www/ponvenue/kestrel-ponvenue.service /etc/systemd/system 
          
    - name: Enable Service
      uses: appleboy/ssh-action@web
      with:
           host: ${{ secrets.HOST }}
           USERNAME: ${{ secrets.USERNAME }}
           PORT: 22
           KEY: ${{ secrets.SSHKEY }}
           script: sudo systemctl enable /var/www/ponvenue/kestrel-ponvenue.service    

    - name: Run Kestrel Service
      uses: appleboy/ssh-action@web
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: systemctl restart kestrel-ponvenue.service
